# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pago_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pago_inicial(object):
    def setupUi(self, pago_inicial):
        pago_inicial.setObjectName("pago_inicial")
        pago_inicial.resize(674, 361)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pago_inicial.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(pago_inicial)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 541, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(pago_inicial)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 19))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(pago_inicial)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 101, 19))
        self.label_7.setObjectName("label_7")
        self.listWidget = QtWidgets.QListWidget(pago_inicial)
        self.listWidget.setGeometry(QtCore.QRect(10, 90, 256, 111))
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(pago_inicial)
        self.label_2.setGeometry(QtCore.QRect(290, 70, 91, 19))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(pago_inicial)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 70, 191, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(pago_inicial)
        self.label_3.setGeometry(QtCore.QRect(290, 110, 101, 19))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(pago_inicial)
        self.label_9.setGeometry(QtCore.QRect(610, 280, 51, 71))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("img/logo2.png"))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(pago_inicial)
        self.label_4.setGeometry(QtCore.QRect(280, 330, 211, 19))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(pago_inicial)
        self.pushButton.setGeometry(QtCore.QRect(510, 320, 88, 27))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(pago_inicial)
        self.label_5.setGeometry(QtCore.QRect(290, 150, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(pago_inicial)
        self.lineEdit_4.setGeometry(QtCore.QRect(400, 150, 191, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(pago_inicial)
        self.label_6.setGeometry(QtCore.QRect(290, 190, 91, 17))
        self.label_6.setObjectName("label_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(pago_inicial)
        self.plainTextEdit.setGeometry(QtCore.QRect(400, 190, 191, 121))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.comboBox = QtWidgets.QComboBox(pago_inicial)
        self.comboBox.setGeometry(QtCore.QRect(400, 110, 191, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(['Restauraciones', 'Endodoncias', 'Extracciones',
         'Cirugias', 'Periodoncias', 'Blanqueamientos', 'Postes', 'Retratamientos', 'Revision', 'Limpiezas', 'Tx', 'Otros'])
        self.label_8 = QtWidgets.QLabel(pago_inicial)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 67, 17))
        self.label_8.setObjectName("label_8")
        self.comboBox_2 = QtWidgets.QComboBox(pago_inicial)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 240, 161, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(['Efectivo', 'Transferencia'])
        self.label_10 = QtWidgets.QLabel(pago_inicial)
        self.label_10.setGeometry(QtCore.QRect(20, 300, 91, 17))
        self.label_10.setObjectName("label_10")
        self.comboBox_3 = QtWidgets.QComboBox(pago_inicial)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 300, 86, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItems(['1', '2'])

        self.retranslateUi(pago_inicial)
        QtCore.QMetaObject.connectSlotsByName(pago_inicial)

    def retranslateUi(self, pago_inicial):
        _translate = QtCore.QCoreApplication.translate
        pago_inicial.setWindowTitle(_translate("pago_inicial", "Pago inicial"))
        self.label.setText(_translate("pago_inicial", "Paciente: "))
        self.label_7.setText(_translate("pago_inicial", "Tratamientos:"))
        self.label_2.setText(_translate("pago_inicial", "Pago Inicial:"))
        self.label_3.setText(_translate("pago_inicial", "Tratamiento:"))
        self.label_4.setText(_translate("pago_inicial", "Fecha: 21/07/2021 13:25:48"))
        self.pushButton.setText(_translate("pago_inicial", "Agregar"))
        self.label_5.setText(_translate("pago_inicial", "Costo Total:"))
        self.label_6.setText(_translate("pago_inicial", "Descripcion:"))
        self.label_8.setText(_translate("pago_inicial", "Pago en:"))
        self.label_10.setText(_translate("pago_inicial", "Consultorio:"))
